artifact_uri: file:///Users/davidsoteloseguin/Library/Mobile Documents/com~apple~CloudDocs/Personal/Formacion
  /Bootcamp/Bootcamp KC/Deep_Learning/DeepLearning/DeepLearning/ProyectoFinal-KC/ProyectoFinalKC/mlruns_david/690685605411448861/93e2b62af399459eac861faa14408822/artifacts
end_time: 1755877372994
entry_point_name: ''
experiment_id: '690685605411448861'
lifecycle_stage: active
run_id: 93e2b62af399459eac861faa14408822
run_name: custom_multimodalnet_mps_v2_20250822_173603
source_name: ''
source_type: 4
source_version: ''
start_time: 1755876964360
status: 3
tags: []
user_id: davidsoteloseguin
