artifact_uri: file:///Users/davidsoteloseguin/Library/Mobile Documents/com~apple~CloudDocs/Personal/Formacion
  /Bootcamp/Bootcamp KC/Deep_Learning/DeepLearning/DeepLearning/ProyectoFinal-KC/ProyectoFinalKC/mlruns_david/328617027444340384/c01e9712cf2a4917aaaa62dc88697d59/artifacts
end_time: 1755847991412
entry_point_name: ''
experiment_id: '328617027444340384'
lifecycle_stage: active
run_id: c01e9712cf2a4917aaaa62dc88697d59
run_name: custom_multimodalnet_mps_20250822_092910
source_name: ''
source_type: 4
source_version: ''
start_time: 1755847751310
status: 3
tags: []
user_id: davidsoteloseguin
